name: Angular-CI
# Controls whn the workflow will run
on:
# Triggers the workflow on push or pull request events ut only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# A workflow run is made up of one or more jobs that can run sequetially or in parallel
jobs:
# This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
    - uses: actions/checkout@v4.1.1
    # Setup Node.js
    - name: Setup nodejs
      uses: actions/setup-node@v4.0.0
      with:
        node-version: "18"
    # Install dependencies
    - name: Install deps
    - run: npm i
    - name: Build app bundle
    - run: npm run build
    # Deploy to Netlify
    - name: Deploy to Netlify
    - uses: nwtgck/actions-netlify@v2.1.0
      with:
      # Publish directory
        publish-dir: './build'
        production-branch: master
        deploy-message: "Deploy from Github Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
